### ISSUE TITLE
Wrong command for setting password

### ISSUE THREAD

**Issue by geekdave** [utkarshcmu/wizzy-site#1]
A few places in the docs say to use:

```
wizzy set grafana username password
```

which should probably be

```
wizzy set grafana password password
```

See:

https://github.com/utkarshcmu/wizzy-site/search?utf8=%E2%9C%93&q=%22wizzy+set+grafana+username+password%22&type=

**Comment by utkarshcmu** [comment]
Fixed, thanks for reporting!
